### ISSUE TITLE
 There was an error with the music player Invalid regular expression: missing /

### ISSUE THREAD

**Issue by dxkyy** [elbkr/music-bot#100]
Ahh, I updated discord-music-player to the newest version, and it works now, ty!

_Originally posted by @dxkyy in https://github.com/elbkr/music-bot/issues/99#issuecomment-1218590253_

Sorry for opening up all these issues, but whenever I do /play, the bot joins the VC and then I get this error: 
```
[18-08-2022 01:07:17]: [Player] There was an error with the music player
Invalid regular expression: missing /
[18-08-2022 01:07:17]: [Player] There was an error with the music player
Invalid regular expression: missing /
```
This also happens for example when I do /search. The bot then joins and I can then send the track number, but when I send the track number I get the same error again.

**Comment by elbkr** [comment]
Can you send the whole error?

**Comment by dxkyy** [comment]
This is the whole log:
```
C:\Users\adrian\Desktop\dev\discord\music-bot>node index.js
[18-08-2022 01:12:38]: [Database] Successfully connected to the database! (Latency: 318ms)
[18-08-2022 01:12:39]: [Ready] Connected into ovy#2980
[18-08-2022 01:12:39]: [Data] Watching 2 servers | 64 members | 80 channels
[18-08-2022 01:12:39]: [Emotes] Loaded emotes!
[18-08-2022 01:12:48]: [Player] There was an error with the music player
Invalid regular expression: missing /
[18-08-2022 01:12:48]: [Player] There was an error with the music player
Invalid regular expression: missing /
```

**Comment by elbkr** [comment]
let me try downloading the template

**Comment by elbkr** [comment]
Hmm very weird, my bot was working correctly but today I tried it without changing anything and it shows me the same error as you. I will look at it.

**Comment by ZeleffOff** [comment]
Hello, I have exactly the same error exactly the same day..
Yesterday everything was working, but today I have this error.

**Comment by elbkr** [comment]
It’d a problem in a package, not in the bot code. We have to wait and hope it works

**Comment by elbkr** [comment]
@ZeleffOff @dxkyy the issue is in `ytdl-core`, you can use this: `npm i ytld-core@4.10.0` while they fix it

**Comment by ZeleffOff** [comment]
> npm i ytld-core@4.10.0

it works perfectly, thanks for the feedback!👍
`npm i ytdl-core@4.10.0` *
