### ISSUE TITLE
Invalid or unexpected token

### ISSUE THREAD

**Issue by Artanisky** [elbkr/music-bot#127]
![image](https://user-images.githubusercontent.com/32029918/206788942-ba82fd9d-97ca-45ce-bc18-2c195b7e5043.png)
![image](https://user-images.githubusercontent.com/32029918/206788992-c691838a-8f18-438c-b89f-8b0ad8ac0347.png)

How to fix? TOKEN and CLIENTID wrote everything correctly

**Comment by Artanisky** [comment]
![image](https://user-images.githubusercontent.com/32029918/206791579-dd309f45-8d6e-433f-a63f-c328ae873dd5.png)
 Nope

**Comment by elbkr** [comment]
Go to src/player/index.js and in:

`player.on("error", (error, queue) => {
        client.logger.error(`

change it with: 

`player.on("error", (error, queue) => {
        console.log(error)
client.logger.error(`

**Comment by Artanisky** [comment]
![image](https://user-images.githubusercontent.com/32029918/206792831-a528dc88-e420-4031-a73c-66f5e55678ae.png)

**Comment by elbkr** [comment]
Send full error

**Comment by Artanisky** [comment]
![image](https://user-images.githubusercontent.com/32029918/206793045-e867e314-d9a8-48ac-997d-03ba1362a060.png)
fulll

**Comment by Artanisky** [comment]
![image](https://user-images.githubusercontent.com/32029918/206794138-4ecb1c80-3def-4a72-b878-532de6a3aee5.png)

**Comment by elbkr** [comment]
Bro I don't know what's wrong bc it works for me. Try to update ytdl-core by using `npm i ytdl-core@latest` and tell me if it worked

**Comment by Artanisky** [comment]
Thank you, it helped
