### ISSUE TITLE
Multi Guild emoji

### ISSUE THREAD

**Issue by inoaa79** [elbkr/music-bot#23]
Hello! How can i add multi guild emoji support?

**Comment by elbkr** [comment]
It's supposed to work in multi guilds with the emojis I specified, the bot just needs the USE_EXTERNAL_EMOJIS permission.
Or did you mean how to let different guilds set their custom emojis?

**Comment by inoaa79** [comment]
> It's supposed to work in multi guilds with the emojis I specified, the bot just needs the USE_EXTERNAL_EMOJIS permission. Or did you mean how to let different guilds set their custom emojis?

I think I add USE_EXTERNAL_EMOJIS perm. But it still didn't work.

**Comment by elbkr** [comment]
Make sure the bot has that perm by going to discord  server setting < roles < the bot role < check if has use externl emojis

**Comment by inoaa79** [comment]
![image](https://user-images.githubusercontent.com/74672207/149669668-2d8957ce-5e93-4e94-9891-201bd2c958ba.png)
Is that perms right?

**Comment by elbkr** [comment]
Yes, I think the problem is that the channel where you run the commands has the `use external emojis` permission disabled for @everyone

**Comment by inoaa79** [comment]
Yes! That's the problem. Thank's for the help!
